CREATE TABLE profile (
	id SERIAL NOT NULL, 
	username VARCHAR NOT NULL, 
	url_profile VARCHAR NOT NULL, 
	url_weapons VARCHAR NOT NULL, 
	kills INTEGER, 
	deaths INTEGER, 
	kd_ratio FLOAT, 
	kill_assists INTEGER, 
	score_min INTEGER, 
	quits INTEGER, 
	mcom_defend_kills INTEGER, 
	mcom_destroyed INTEGER, 
	flags_captured_conquest INTEGER, 
	flags_defended_conquest INTEGER, 
	vehicles_destroyed INTEGER, 
	vehicles_destroyed_assists INTEGER, 
	avg_weapon_accuracy FLOAT, 
	longest_headshot FLOAT, 
	highest_kill_streak INTEGER, 
	skill FLOAT, 
	avenger_kills FLOAT, 
	savior_kills INTEGER, 
	dogtags_taken INTEGER, 
	flags_captured_ctf INTEGER, 
	squad_score_bonus FLOAT, 
	repairs INTEGER, 
	revives INTEGER, 
	heals INTEGER, 
	resupplies INTEGER, 
	shots_fired INTEGER, 
	highest_nemesis_streak INTEGER, 
	nemesis_kills INTEGER, 
	suppression_assists INTEGER, 
	PRIMARY KEY (id), 
	UNIQUE (username)
)